# Generated by Django 3.0.5 on 2020-04-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='name',
            new_name='title',
        ),
    ]
