# Generated by Django 3.0.5 on 2020-04-23 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200424_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 2, 36, 41, 833932)),
        ),
    ]
