# Generated by Django 3.0.5 on 2020-04-23 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200424_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='Без категорий', on_delete=django.db.models.deletion.CASCADE, to='todo.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 4, 52, 28, 115042)),
        ),
    ]
