# Generated by Django 3.0.5 on 2020-04-23 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20200424_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 4, 59, 30, 420893)),
        ),
    ]
