# Generated by Django 3.0.5 on 2020-04-23 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20200424_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 23, 23, 5, 36, 817042, tzinfo=utc)),
        ),
    ]
