# Generated by Django 3.0.5 on 2020-04-24 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20200424_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
